### ISSUE TITLE
federated_main.py运行有问题

### ISSUE THREAD

**Issue by fengyann** [AshwinRJ/Federated-Learning-PyTorch#15]
Traceback (most recent call last):
  File "federated_main.py", line 33, in <module>
    torch.cuda.set_device(args.gpu)
  File "D:\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 243, in set_device
    device = _get_device_index(device)
  File "D:\Anaconda3\lib\site-packages\torch\cuda\_utils.py", line 20, in _get_device_index
    device = torch.device(device)
RuntimeError: Expected one of cpu, cuda, mkldnn, opengl, opencl, ideep, hip, msnpu device type at start of device string: 0

**Comment by littlejiumi** [comment]
torch.cuda.set_device(int(args.gpu))
